### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shadow-walker4** [evildevill/instainfo#15]
Attempt to login...Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/shadow_walker4/instainfo/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shadow_walker4/instainfo/instainfo.py", line 122, in <module>
    api = instainfo(args.id, args.file, args.json, args.command, args.output, args.cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shadow_walker4/instainfo/src/instainfo.py", line 48, in __init__
    self.setTarget(target)
  File "/home/shadow_walker4/instainfo/src/instainfo.py", line 61, in setTarget
    self.following = self.check_following()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shadow_walker4/instainfo/src/instainfo.py", line 1159, in check_following
    return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shadow_walker4/instainfo/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/home/shadow_walker4/instainfo/venv/lib/python3.11/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

**Comment by Sboyrikku-icloud** [comment]
This should help you identify the issue and potentially fix the problem.

```python
import instagram_private_api

# ...

endpoint = self.api._get_endpoint('user_detail')
print(f"Endpoint URL: {endpoint}")
response = self.api._call_api(endpoint)
```
